In [27]:
import pandas as pd

In [28]:
attr = pd.read_csv("../data/raw/attributes.csv")
attr["attributes"] = attr["attributes"].str.strip()  # Remove leading/trailing whitespace from the attribute_name column
attr.head()

      attributes
0          state
1         county
2      community
3  communityname
4           fold

In [29]:
df = pd.read_csv('../data/raw/communities.data', names = attr['attributes'])
df.head()

,state,county,community,communityname,fold,population,householdsize,racepctblack,racePctWhite,racePctAsian,...,LandArea,PopDens,PctUsePubTrans,PolicCars,PolicOperBudg,LemasPctPolicOnPatr,LemasGangUnitDeploy,LemasPctOfficDrugUn,PolicBudgPerPop,ViolentCrimesPerPop
0,8,?,?,Lakewoodcity,1,0.19,0.33,0.02,0.90,0.12,...,0.12,0.26,0.20,0.06,0.04,0.9,0.5,0.32,0.14,0.20
1,53,?,?,Tukwilacity,1,0.00,0.16,0.12,0.74,0.45,...,0.02,0.12,0.45,?,?,?,?,0.00,?,0.67
2,24,?,?,Aberdeentown,1,0.00,0.42,0.49,0.56,0.17,...,0.01,0.21,0.02,?,?,?,?,0.00,?,0.43
3,34,5,81440,Willingborotownship,1,0.04,0.77,1.00,0.08,0.12,...,0.02,0.39,0.28,?,?,?,?,0.00,?,0.12
4,42,95,6096,Bethlehemtownship,1,0.01,0.55,0.02,0.95,0.09,...,0.04,0.09,0.02,?,?,?,?,0.00,?,0.03

In [30]:
df.shape

(1994, 128)

In [31]:
df.to_csv('../data/raw/communities.csv', index=False)

In [33]:
df = pd.read_csv('../data/raw/communities.csv')
df.shape

(1994, 128)

In [34]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1994 entries, 0 to 1993
Columns: 128 entries, state to ViolentCrimesPerPop
dtypes: float64(100), int64(2), str(26)
memory usage: 1.9 MB